### ISSUE TITLE
view里面的文字的位置能不能进行居中

### ISSUE THREAD

**Issue by wangxueyou110** [Kujiale-Mobile/Painter#1]
view里面的文字的位置能不能进行居中

**Comment by CPPAlien** [comment]
请问你指的居中是啥意思？目前可以通过 left，top，right，bottom 来把文字放在任何位置上的

**Comment by wangxueyou110** [comment]
就是文字内容居中，但是文字的字数不确定

**Comment by wangxueyou110** [comment]
![image](https://user-images.githubusercontent.com/30291910/42306981-8ef71244-8063-11e8-8be2-2c62ccfc4fe3.png)
就是这一种

**Comment by CPPAlien** [comment]
目前这个属性还没有支持。近期我们会进行支持，如果您有兴趣，也欢迎发 PR

**Comment by CPPAlien** [comment]
@wangxueyou110 你好，该功能已支持，你可以 pull 下最新代码，注意，需要执行 git submodule update 一下。你可以在任何子 view 的 css 中添加 align 属性进行对齐方式的选择，目前有 center，left，right 可供选择。其中 left 为默认方式

**Comment by wangxueyou110** [comment]
还有个问题，因为很多分享出去的上面的头像，二维码都是圆形的，可以弄成圆形的吗

**Comment by CPPAlien** [comment]
可以的，可以设置 borderRadius 属性，当为一半宽度时，就是圆形了，见文档

**Comment by wangxueyou110** [comment]
好的

**Comment by CPPAlien** [comment]
@GPPoseidon999 可以另开 issue，截图描述下

**Comment by CPPAlien** [comment]
@GPPoseidon999 可以另开 issue，截图描述下

**Comment by wangxueyou110** [comment]
@GPPoseidon999 我是生效的啊
