### ISSUE TITLE
安卓手机mpvue框架里canvas生成图片的时候有问题

### ISSUE THREAD

**Issue by brandyjoxic** [Kujiale-Mobile/Painter#100]
测的一个是华为的P10plus，在mpvue框架内canvas绘制好后会在@imgErr的函数里报错  错误为：canvasToTempFilePath failed,{'errMsg‘:canvasToTempFilePath: fail canvas is empty} 虽然原生小程序也有这个问题 请问有别的解决方案吗？

**Comment by brandyjoxic** [comment]
问题已解决，fail canvas is empty 通过改代码里的settimeout的时间可以解决。但触发了代码里的getImageInfo的The result is always fault, even we tried 5 times的问题。虽然不太懂比例相符是要干什么。。。但是我还是让他输出临时文件而不是强制重绘制就好了。感谢！

**Comment by CPPAlien** [comment]
因为canvas 图片有时候会绘制出错，这边要校验一下
