### ISSUE TITLE
mpvue版本  绘制完会大概率出现 文本错乱 大小 颜色

### ISSUE THREAD

**Issue by cxh1991** [Kujiale-Mobile/Painter#105]
mpvue版本  绘制完会大概率出现 文本错乱 大小 颜色 还有加载图片特别慢 经常导致 shareImage没有获取到海报路径 而报错

**Comment by CPPAlien** [comment]
mpvue 相关问题，可以到：https://github.com/Kujiale-Mobile/Mpvue-Painter-Demo 下说明
