### ISSUE TITLE
生成二维码的大小很难控制

### ISSUE THREAD

**Issue by jmy08** [Kujiale-Mobile/Painter#11]
![](http://kl-widget.b0.upaiyun.com/forUpload/20180712101234.png)
![](http://kl-widget.b0.upaiyun.com/forUpload/20180712101240.png)

**Comment by CPPAlien** [comment]
OK ，这个问题我们收到了，我们近期会看下这个问题

**Comment by jmy08** [comment]
好的哦 ~感谢

**Comment by CPPAlien** [comment]
目前边框你可以用 rect 实现的，rect 作为背景，虽然有点麻烦，不过倒是可以实现，border 属性后续会考虑下

**Comment by jmy08** [comment]
嗯 目前正在采用这个办法实现border 期待后续新增border~感谢

**Comment by CPPAlien** [comment]
@jmy08 二维码问题已经修复，你可以再看下

**Comment by jmy08** [comment]
好的 感谢。
