### ISSUE TITLE
安卓生成图片带有换行符文字不换行

### ISSUE THREAD

**Issue by ichizi** [Kujiale-Mobile/Painter#112]
安卓表现如下
![WechatIMG108](https://user-images.githubusercontent.com/7540755/56400547-0bd31280-6287-11e9-8dfe-bdd0a0ba0eca.png)

IOS表现如下
![WechatIMG292](https://user-images.githubusercontent.com/7540755/56400558-142b4d80-6287-11e9-966e-a1f0548d4d12.jpeg)

另外若若的问一句，为啥安卓会有些字符无法识别变成？有何种解决方案么？

**Comment by CPPAlien** [comment]
是啊，这个是需要加入的 feature，目前换行符不支持

**Comment by CPPAlien** [comment]
目前已支持
