### ISSUE TITLE
做的弹出层，Painter的层级太高  怎么解决

### ISSUE THREAD

**Issue by chaojiangcn** [Kujiale-Mobile/Painter#115]
在真机显示这样的问题

**Comment by CPPAlien** [comment]
可以用生成的图片，而不是直接用 painter

**Comment by chaojiangcn** [comment]
就是海报的一个内容文案是可以编辑的，我设置了可以输入的弹出层  模拟器上功能是可以实现的，但是跑在真机就是层级太低 试了小程序的<cover-view>勉强可以解决我的这个问题，看看有没有更好的方法
