### ISSUE TITLE
文字+padding+background+radius 会出现背景和文字都被圆角

### ISSUE THREAD

**Issue by hongchengfhc** [Kujiale-Mobile/Painter#118]
<img width="84" alt="WX20190513-094413@2x" src="https://user-images.githubusercontent.com/17824466/57591425-dd81e380-7563-11e9-838f-e67fdc8a2fc7.png">
做一个这样的效果  却出来这样的
<img width="84" alt="WX20190513-094912@2x" src="https://user-images.githubusercontent.com/17824466/57591518-6ac53800-7564-11e9-8b0c-40cd1e41bf65.png">

**Comment by CPPAlien** [comment]
背景可以用 rect
