### ISSUE TITLE
苹果安卓都会出现这种情况--->背景、图片不能显示？

### ISSUE THREAD

**Issue by heroFan** [Kujiale-Mobile/Painter#12]
![Uploading 1531453000.jpg…]()
麻烦作者看下是什么问题？（二维码、文字能正常显示）

**Comment by CPPAlien** [comment]
真机上运行，需要添加网络图片地址为合法域名，或者你可以开启调试模式

**Comment by heroFan** [comment]
远程调试已经启动不效验合法域名也会出现这个问题呢！不知道你那边能不能复现？

**Comment by CPPAlien** [comment]
我们这边真机是没有问题的，可以说下您使用的微信版本和真机型号吗？
