### ISSUE TITLE
通过文本中的换行符进行主动换行,这个问题什么时候解决呢

### ISSUE THREAD

**Issue by houyanchao** [Kujiale-Mobile/Painter#123]

**Comment by BruceGujinhe** [comment]
发现1个 `\n`可以换行，多个就不行了。
另外是否能支持英文单词换行呢？

**Comment by kiteliu** [comment]
iOS 支持文字换行，android不行

**Comment by kiteliu** [comment]
文本中的换行符android不支持啊

**Comment by BruceGujinhe** [comment]
不需要这个换行。利用空格就行。

**Comment by CPPAlien** [comment]
主动换行已支持，请 pull 最新代码， https://github.com/Kujiale-Mobile/Painter/pull/137

**Comment by fernandoxu** [comment]
> 不需要这个换行。利用空格就行。下面是我自己研究出来的方法。
> 基本原理：
> 
> * 将英文拆分成单词为单位，然后做个和指定宽度做比较，小于就追加到当前行，否则就生成新的一行。
> * 然后再通过格式化函数处理刚才拆分的字符数组
> * 高度是动态变化的，需要在生成最终template.views处进行处理。
> 
> ```
> /**
>  * 根据输入文字进行分割
>  * @param abc
>  * @returns {Array}
>  */
> export function calculateLines (abc, width) {
>   // let abc = 'abc def de false wefa'
>   console.log('abc:', abc)
>   let tmp = []
>   let result = []
>   let exabc = abc.split(' ')
>   exabc.forEach((item, index) => {
>     let newLine = tmp.join(' ').concat(' ').concat(item)
>     if (newLine.length > width) {
>       result.push(tmp.join(' '))
>       tmp = []
>       newLine = ''
>       tmp.push(item)
>     } else {
>       tmp.push(item)
>     }
>   })
>   if (tmp.length > 0) {
>     result.push(tmp.join(' '))
>   }
>   console.log('result:', result)
>   return result
> }
> 
> export function getTextFormatData (text, top) {
>   return {
>     type: 'text',
>     text: text,
>     css: {
>       top: top + 'px',
>       left: '143px',
>       width: '192px',
>       align: 'center',
>       fontWeight: 'bold',
>       fontSize: '14px',
>       lineHeight: '19px',
>       color: '#111111'
>     }
>   }
> }
> ```
> 
> 使用：
> 
> ```
> this.chineseLabel = obj.chineseLabel
> this.englishLabel = obj.englishLabel
> let template = this.getTemplateData()
> console.log('template: ', this.template)
> let moreLines = calculateLines(this.englishLabel, 30) // 每行最多不超过30个字符
> console.log('morelines', moreLines)
> let top = 200
> moreLines.forEach(item => {
>   let formatData = getTextFormatData(item, top)
>   console.log('formatData: ', formatData)
>   top += 20
>   template.views.push(formatData)
> })
> template.views.push(getTextFormatData(this.chineseLabel, top))
> this.template = template
> ```

中英文混排的一句话怎么做😂
