### ISSUE TITLE
怎么设置image和qrcode 水平居中呢

### ISSUE THREAD

**Issue by buhtib** [Kujiale-Mobile/Painter#126]
怎么设置image和qrcode 水平居中呢

**Comment by CPPAlien** [comment]
因为 image 和 qrcode 肯定是固定长宽的，所以你可以自己计算咯

**Comment by buhtib** [comment]
//left设为 最外层盒子宽度的一半 align: 'center' 时为水平居中
{
width:xxx
 {
          type: 'image',
          url: ,
          css: {
            left: (width / 2) 
            align: 'center',
          },
        },
}


我发现这样子就能居中了:smirk:
