### ISSUE TITLE
合成图片太大

### ISSUE THREAD

**Issue by lvdong** [Kujiale-Mobile/Painter#127]
背景图160k,小程序码图片106k,因为要生成776*1366像素的。所以设置宽高比较大，合成后发现图片大小达到将近700k，能不能支持压缩

**Comment by shuliuzhenhua** [comment]
看我提交的 Issues 已经关闭了，因为默认绘制还会 乘 屏幕像素密度，所以你图片的实际高度是 776 * 密度，在 Iphonex 上面就是  2328 当然会很大。

**Comment by CPPAlien** [comment]
这块确实可以优化下，让外层自定，当初这样考虑是为了保证在所有机型上不会显的模糊

**Comment by CPPAlien** [comment]
已支持由外层设置 widthPixels 来写死生成的图片像素宽度
