### ISSUE TITLE
Painter 画板层级问题

### ISSUE THREAD

**Issue by minimalistrojan** [Kujiale-Mobile/Painter#130]
### 需求：

想要实现一个类似下图这样的效果：

![155855ytuz9bzlmb3m9xlz](https://user-images.githubusercontent.com/22811809/59580944-be97e380-9105-11e9-9158-745036e8dcee.gif)

黑色区域是 `<painter>` ，tabbar 是固定的一块，里边包含一个 `<input>` 和 `<button>` 。

### 问题：

在真机上，黑色区域会覆盖 tabbar 。查了查，说是小程序使用的是 `<canvas>` 原生组件，层级最高。可以使用 `<cover-view>` 跨越层级，但是它里边不能包含 `<input>` 。

大佬们有遇到类似问题吗，有什么好的解决方案？

感谢。

**Comment by CPPAlien** [comment]
如果是层级问题，可以使用 painter 生成后的图片，而不要直接放 painter，可以把 painter 移到屏幕外来绘制，得到图片后显示就行

**Comment by minimalistrojan** [comment]
好的，我试试。感谢大佬回复。
