### ISSUE TITLE
是否可以支持 uni-app

### ISSUE THREAD

**Issue by hedeqiang** [Kujiale-Mobile/Painter#131]
请问能否支持 uni-app ？

**Comment by yuanxiongwei** [comment]
现在不支持，估计不会弄吧。很遗憾啊

**Comment by wonxll** [comment]
uni-app 里可以用，但是在 ios 13 上会有问题，不知道是painter的问题，还是uni-app的问题

**Comment by wonxll** [comment]
@CPPAlien

**Comment by yuanxiongwei** [comment]
@wonxll  在uni-app下如何使用？
@CPPAlien 能否针对uni-app进行兼容调整，很期待

**Comment by xzusoft** [comment]
在uni-app中如何使用有人搞出来了吗

**Comment by leohowl** [comment]
> 在uni-app中如何使用有人搞出来了吗

uniapp 可以原生的小程序组件，但是只能在小程序里面使用 [小程序组件支持](https://uniapp.dcloud.io/frame?id=%e5%b0%8f%e7%a8%8b%e5%ba%8f%e7%bb%84%e4%bb%b6%e6%94%af%e6%8c%81)

**Comment by zccbillion** [comment]
我用微信小程序组件的方式用了，然后，小程序使用没问题，但是，在APP里使用绘制出来图像只有图片没有文字，所有文字都绘制不出来，不知什么原因

**Comment by zccbillion** [comment]
我用微信小程序组件的方式用了，然后，小程序使用没问题，但是，在APP里使用绘制出来图像只有图片没有文字，所有文字都绘制不出来，不知什么原因
