### ISSUE TITLE
是否支持给文字 view 设置高度或 padding-bottom ？

### ISSUE THREAD

**Issue by minimalistrojan** [Kujiale-Mobile/Painter#132]
### 需求
给文本设置圆角矩形边框，文字水平垂直居中，并且周围留出一些 padding 。

### 问题
试着改了一下 Demo 中的代码，发现：
1. 给文字 view 设置 height 无效；
2. 看到可以设置 padding 属性，但似乎只作用于 padding-top 。

希望将来可以支持设置文本 view 高度和 padding-bottom 。另外，对于这个需求，目前有什么好的解决方案吗？感谢。

**Comment by CPPAlien** [comment]
padding 是有效的吧，你设置个 background 加 padding 试试

**Comment by minimalistrojan** [comment]
<img width="1174" alt="Xnip2019-06-21_22-16-40" src="https://user-images.githubusercontent.com/22811809/59928970-6ef14900-9472-11e9-8991-dfb71b4396dd.png">
直接在 demo 上改的。看样子是只对 padding-top 和 padding-right 有效。

**Comment by CPPAlien** [comment]
是有效的，只是底部是另一个 view 了
