### ISSUE TITLE
通过换行符进行主动换行和图片清晰度，是否可以支持下？

### ISSUE THREAD

**Issue by houyanchao** [Kujiale-Mobile/Painter#133]
换行符进行主动换行，这个是你们todo里的计划，啥时候支持下这个功能？

是否可以多加一个配置参数，来控制图片清晰度。比如默认是1，设置为2的时候，图片会更清晰

**Comment by CPPAlien** [comment]
换行符已支持，图片清晰度已排期

**Comment by CPPAlien** [comment]
图片清晰度已支持，见更新文档

**Comment by houyanchao** [comment]
> 换行符已支持，图片清晰度已排期

赞
