### ISSUE TITLE
fontFamily是不支持的

### ISSUE THREAD

**Issue by Brokenstrings** [Kujiale-Mobile/Painter#134]
![image](https://user-images.githubusercontent.com/7030227/60488028-6f3fde80-9cd3-11e9-8beb-fc923369d215.png)

**Comment by shiyuanjieyi** [comment]
我就纳闷了，开发工具上测试可以，但是真机就不行

**Comment by nailuoGG** [comment]
这个是小程序的问题，canvas不支持定义字体

**Comment by nailuoGG** [comment]
这个是小程序的问题，canvas不支持定义字体
