### ISSUE TITLE
线上环境在线url图片无法显示 但是体验版 真机调试等 都是正常的

### ISSUE THREAD

**Issue by fangkyi03** [Kujiale-Mobile/Painter#143]
http://img3.nongbaxian.com.cn/2019-07/3aef6c96-cb7e-401b-96b9-2a3c1b20fdb1.2348826499991110914.8980/userfiles/fileupload/201907/1150580068971610114.jpg
图片地址是这个 正式环境无法显示
但是体验版 真机调试都是能够正常显示的 不知道为何正式环境不行 而且只是在线url有这个问题 本地图片没问题

**Comment by fangkyi03** [comment]
因为https的关系 已经找到原因

**Comment by alanhg** [comment]
> 因为https的关系 已经找到原因

https怎么了？报错？
