### ISSUE TITLE
怎么实现文字每一行的开头不是标点符号呢？

### ISSUE THREAD

**Issue by fernandoxu** [Kujiale-Mobile/Painter#144]
默认的情况
![微信图片编辑_20190730163352](https://user-images.githubusercontent.com/20871468/62113983-3f8ef100-b2e8-11e9-85fd-48dc8f36ac0b.jpg)

**Comment by minchangyong** [comment]
控制字体大小。

**Comment by fernandoxu** [comment]
@minchangyong 字体大小只能用px，所以无法适配不同手机呀

**Comment by CPPAlien** [comment]
字体可以用 rpx，Painter 会转

**Comment by fernandoxu** [comment]
@CPPAlien 调字体还是避免不了标点符号出现在行首吧, 只能到行尾了判断
