### ISSUE TITLE
mpvue 无法触发 imgOK，官方例子也无法触发。

### ISSUE THREAD

**Issue by epicmr** [Kujiale-Mobile/Painter#145]
![image](https://user-images.githubusercontent.com/12428380/62183419-ab2a9a00-b38c-11e9-860d-a344c838c0ce.png)

**Comment by mixsun** [comment]
也遇到了 监听不到imgOK事件  看源码里面也有  that.$emit('imgOK', { path: filePath }); 绑定

**Comment by epicmr** [comment]
onImgOK 这个地方错了。OK 的大小写搞错了
