### ISSUE TITLE
The result is always fault, even we tried 5 times

### ISSUE THREAD

**Issue by houyanchao** [Kujiale-Mobile/Painter#149]
查不出什么原因，总是报：The result is always fault, even we tried 5 times 这个错误

json代码如下：
{
      background: '#eeeeee',
      width: '750rpx',
      height: '600rpx',
      borderRadius: '20rpx',
      views: [
      {
        type: 'image',
        url: 'https://qhyxpicoss.kujiale.com/r/2017/12/04/L3D123I45VHNYULVSAEYCV3P3X6888_3200x2400.jpg',
        css: {
          top: '48rpx',
          right: '48rpx',
          width: '192rpx',
          height: '192rpx',
        },
      }
      ]
    }

**Comment by CPPAlien** [comment]
看不出来，可能是图片过大，而你使用的设备内存太小了
