### ISSUE TITLE
text类型要是能自定义font-family就好了

### ISSUE THREAD

**Issue by Coderakang** [Kujiale-Mobile/Painter#15]
fontFamily能支持吗

**Comment by CPPAlien** [comment]
已支持

**Comment by donly** [comment]
根据[官方文档](https://developers.weixin.qq.com/miniprogram/dev/api/wx.loadFontFace.html)：

> canvas等原生组件不支持使用接口添加的字体

发现无法设置字体，loadFontFace 的字体没起作用。

loadFontFace 成功回调后设置：

index.js 相关代码：
```js
this.setData({
  loaded: true,
  template: new Couplet().palette(),
});
```

index.wxml 页面内容：
```xml
<painter wx:if="{{loaded}}" customStyle='margin-left:54rpx;margin-top:40rpx;' palette="{{template}}" bind:imgOK="onImgOK" />
```

palette 代码：
```js
{
  type: 'text',
  text: '我设置了maxLines为1，看看会产生什么效果',
  css: [{
    fontFamily: 'Bitstream Vera Serif Bold',
    top: `${startTop + 7 * gapSize}rpx`,
    width: '400rpx',
    maxLines: 1,
  }, common],
},
```

**Comment by donly** [comment]
基础库 `2.1.2` 只是解决了在模拟器能够显示字体，见[官方贴子](https://developers.weixin.qq.com/community/develop/doc/000260d88ccd18a692f60b88251800)。

难道目前无解？

**Comment by CPPAlien** [comment]
你可以试下使用：http://transfonter.org/ 用这个网站把字体文件 base64 的，直接放到 app.wxss 中以 @font-face 形式加上，看看行不行，再不行就没办法了。

**Comment by CPPAlien** [comment]
那就没办法了，期望以后会支持
