### ISSUE TITLE
如何获取文字 View 行数

### ISSUE THREAD

**Issue by minimalistrojan** [Kujiale-Mobile/Painter#152]
现在有这样一个需求：
两个文字 view ，上边是标题，下边是作者。标题行数不确定（一行或两行），想要实现作者和标题之间的间距固定，因此只能根据标题的行数调整作者 view 的定位（top）。
 
但是，问题是如何获取或计算标题 view 的行数呢？看了看 issue 里一些朋友的类似需求，有一种方法是通过字符数计算文本总长度，然后除以 view 宽度得出行数，但是这样中英文混排有误差。看了看源码，看到里边计算行数也是类似的思路，使用了 canvas 的 `measureText()` 更精确了，但是在 palette 中如何这样计算。
 
有什么更好的方法吗？希望得到大佬的解答。感谢。

**Comment by houyanchao** [comment]
一行的文本的高度可以通过wx.createSelectorQuery().selectAll('class')获取到，一段文本的高度也可以通过它获取到，两者采用相同的css，然后第二个高度除以第一个高度，就大致得行数

**Comment by minimalistrojan** [comment]
您指的是 wxml 中的文本 view 吧。我是指 Painter 绘制的 canvas 画布中的文本 view 。在 `/palette/index.js` 文件中描述绘制的 view 的参数时需要计算绘制的标题的 view 的行数。

**Comment by houyanchao** [comment]
先从wxml中的同级js里获取行数，再把行数带到palette/index.js中

**Comment by minimalistrojan** [comment]
明白了，感谢。
