### ISSUE TITLE
text一行内字体不一样怎么实现？

### ISSUE THREAD

**Issue by LiweiDong** [Kujiale-Mobile/Painter#161]
比如 倒计时**50**天  

数字50是突出显示的一个大字体

**Comment by CPPAlien** [comment]
只能分开绘制了

**Comment by LiweiDong** [comment]
好吧  只是这个数字宽度不好判断  位数不一样

**Comment by shiyuanjieyi** [comment]
有两种思路：
1、用作者提供的获取文字宽度来在50后面添加剩下文字，但这种方法稍微比较麻烦，要分段渲染；
2、根据特殊字体的字符串宽度来给原段落增加空格，来实现效果，代码如下：
`// 对部分数字生成空格间距
function _space(number) {
  let str = '    ';
  for (let i = 0; i < number.toString().length; i++) {
    str += '  ';
  }
  return str;
}`
上面的空格具体可调
