### ISSUE TITLE
设置背景图片的海报

### ISSUE THREAD

**Issue by StreetFlaneur** [Kujiale-Mobile/Painter#162]
请问下，有背景图片的海报，先画一张背景图，然后后面画的内容会覆盖着前面的元素上面吗？

**Comment by shiyuanjieyi** [comment]
这个自己尝试就知道了，另外请认真看文档

**Comment by fly-sheep** [comment]
> 这个自己尝试就知道了，另外请认真看文档

你好，如果绘制的文字是动态生成的，高度不确定，而其背景是一张图片，图片的高度由文字内容撑开，这种场景要怎么解决呢？
