### ISSUE TITLE
从基础库 1.9.90 开始：setFillStyle、setGlobalAlpha、setLineWidth等已废弃接口

### ISSUE THREAD

**Issue by feelslive** [Kujiale-Mobile/Painter#168]
https://developers.weixin.qq.com/miniprogram/dev/api/canvas/CanvasContext.setFillStyle.html
希望大佬可以在下个版本中更新到最近接口，谢谢！
![image](https://user-images.githubusercontent.com/20579220/65824791-0996ca80-e2a1-11e9-8f91-9ad1807088d4.png)

**Comment by u2shijian** [comment]
期待更新。
