### ISSUE TITLE
咨询，如何在image下面绘制内容

### ISSUE THREAD

**Issue by ichizi** [Kujiale-Mobile/Painter#169]
因为图片高是不固定的，每张卡片最终生成的最终高度也可能不一致
这种情况下如何在图片下面继续输入文本，如下图所示
中间的截图高度不固定，那么下面的那个“网易云音乐”如何定位位置？
 
<img width="366" alt="截屏2019-10-12下午11 16 38" src="https://user-images.githubusercontent.com/7540755/66703550-689b1b80-ed46-11e9-86ad-f41ad01e2094.png">

**Comment by lcaminy** [comment]
先想办法取图片的高度。哪怕是用下载，然后再绘制其他元素。也可以根据上面图片的ID 做新的基点做向下规划

**Comment by ichizi** [comment]
谢谢 图片问题已经解决了，又遇到了新问题，
文本高度有没有办法计算啊？
现在遇到一个问题是 文本高度也不确定。
所以导致整个生成卡片的最终高度无法计算。

**Comment by lcaminy** [comment]
你可以阅读 pen.js 的源码，作者以及针对文字的写入有高度的计算。你可以记录一个全局高度的累加。可以参考 globalTextWidth 的实现 来针对变动的高度做优化，我修改了部分源码。支持已最后的高度元素为基点向下扩展高度元素。一下代码是我修改的两个地方。你可以对比原始代码比较一下。
 `paint(callback) {
    this.style = {
      width: this.data.width.toPx(),
      height: this.data.height.toPx(),
    };
    this._background();
    for (const view of this.data.views) {
      this._drawAbsolute(view);
    }
    console.log("this.globalMaxY:" + this.globalMaxY + ",globalMaxHeight:" + this.style.height);
    console.log(this.globalTextHeight);
    if (this.globalMaxY > this.style.height) {
      this.style.height = this.globalMaxY;
      if (typeof this.changeHeightFn === "function") {
        this.changeHeightFn(this.style.height, () => {
          this._background();
          for (const view of this.data.views) {
            this._drawAbsolute(view);
          }
          console.log(this.globalTextHeight);
          this.ctx.draw(false, () => {
            callback();
          });
        });
      }

    } else {
      this.ctx.draw(false, () => {
        callback();
      });
    }

  }`

`_preProcess(view, notClip) {
.....
 let y;
    if (view.css && view.css.bottom) {
      y = this.style.height - height - view.css.bottom.toPx(true);
    } else {
      if (view.css && view.css.top) {
        if (typeof view.css.top === 'string') {
          y = view.css.top.toPx(true);
        } else {
          const tops = view.css.top;
          y = tops[0].toPx(true) + this.globalTextHeight[tops[1]] * (tops[2] || 1);
        }
      } else {
        y = 0
      }
    }
    if (view.id) {
      this.globalTextHeight[view.id] = height + y;
    }
    if (this.globalMaxY < (height + y)) {
      this.globalMaxY = height + y;
    }
....
}`

**Comment by CPPAlien** [comment]
可以采用设置 id 的方式
