### ISSUE TITLE
根据文本区域高度布局

### ISSUE THREAD

**Issue by sowee121** [Kujiale-Mobile/Painter#171]
上一段文字高度是动态变化的，想知道下一个元素的定位，该怎么处理呢？与根据文本区域宽度布局方法一样吗？

**Comment by CPPAlien** [comment]
https://github.com/Kujiale-Mobile/Painter/pull/173 有个 PR 可以关注下

**Comment by CPPAlien** [comment]
已支持，请 pull 最新代码，方法和 宽度获取一样

**Comment by sowee121** [comment]
> 已支持，请 pull 最新代码，方法和 宽度获取一样

奶思！

**Comment by fly-sheep** [comment]
你好，如果文本区域背景是一张图片，图片高度也需要由文本高度确定，这种情况怎么解决呢？

> 已支持，请 pull 最新代码，方法和 宽度获取一样
