### ISSUE TITLE
borderWidth设置后 borderRadius就不生效了

### ISSUE THREAD

**Issue by cwy930618cwy** [Kujiale-Mobile/Painter#178]
this.paintTestList.views.push(
        {
          type: 'image',
          url: '/common/image/erweima.png',
          css: {
            top: 1207 - this.pictureHeader + 'rpx',
            left: '50rpx',
            width: '164rpx',
            height: '164rpx',
            borderWidth: '10rpx',
            borderColor: 'white',
            borderRadius: '0rpx'
          },
        },
生成的图片边框还是圆角10rpx的 预期是边框宽度是10rpx 边框圆角是0

**Comment by 0JARVIS0** [comment]
最新版painter已修复该问题
