### ISSUE TITLE
多行状态下最后一行的对齐问题

### ISSUE THREAD

**Issue by semi-xi** [Kujiale-Mobile/Painter#18]
按照css写法的话如果设置了多行的情况而且是`align:center`，那样最后一行是也应该是居中的，不确定其他人会不会有这样的一个需求。
我的想法是如果我设置了`align: center`那样，哪怕是你设置了width，在里面的内容也应该是居中的，所以我改了一下你的代码
```
let posX = 0;
      if(align == 'center') {
        posX = -(measuredWith / 2);
      } else {
        posX = -(width / 2);
      }
      this.ctx.fillText(text, posX, -(height / 2) + (i === 0 ? view.css.fontSize.toPx() : (view.css.fontSize.toPx() + i * lineHeight)));
```

改之前：
![image](https://user-images.githubusercontent.com/7565129/42927080-ec214edc-8b65-11e8-8a35-aabc5f216d06.png)

改之后
![image](https://user-images.githubusercontent.com/7565129/42927068-dd8fade6-8b65-11e8-8e42-c8cc83424a22.png)

**Comment by CPPAlien** [comment]
嗯嗯，是应该这样的。 不过需要同时考虑 left，right，center，后续如果加入换行符的处理，这样做的意义也会更大一点。如果您有兴趣的话，欢迎 发 PR

**Comment by semi-xi** [comment]
@CPPAlien  我发现了一个bug，想修复，但是发现没有dev分支，这样的话我是直接pr到master?

**Comment by CPPAlien** [comment]
嗯
