### ISSUE TITLE
mpvue中imgOk无效

### ISSUE THREAD

**Issue by xxj95719** [Kujiale-Mobile/Painter#19]
没有输出

**Comment by CPPAlien** [comment]
贴下代码

**Comment by lihuangshuaige** [comment]
我也不输出

**Comment by CPPAlien** [comment]
@lihuangshuaige 用的例子代码吗？

**Comment by shuliuzhenhua** [comment]
@xxj95719  可以参考这个 https://github.com/Kujiale-Mobile/Painter/pull/106

**Comment by RocketV2** [comment]
> @xxj95719 可以参考这个 #106

按照#106写法 貌似还是不行

**Comment by RocketV2** [comment]
> @shuliuzhenhua可以参考这个 #106

**Comment by RocketV2** [comment]
> @shuliuzhenhua 可以参考这个 #106

按照#106貌似还是不行
