### ISSUE TITLE
是否有 wepy 的版本呢

### ISSUE THREAD

**Issue by wyh888** [Kujiale-Mobile/Painter#20]
如题

**Comment by CPPAlien** [comment]
是否支持这些框架，就看这些框架是否支持引入小程序的原生组件了，如果 wepy 支持使用小程序自己的 component 组件就可以

**Comment by hjyue1** [comment]
@wyh888 正好用到这个，顺便做了一个wepy版本 https://github.com/hjyue1/painter-wepy

**Comment by chenillen** [comment]
楼上贡献满满，就是好像用起来有些问题。

**Comment by hjyue1** [comment]
@chenillen 可以提交issues给我哈

**Comment by chenillen** [comment]
@hjyue1 已經提了哈。
