### ISSUE TITLE
使用过程中有几个问题想问下

### ISSUE THREAD

**Issue by CodingZJ** [Kujiale-Mobile/Painter#207]
1. 如果绘制的图片超过一屏幕，绘制长图支持吗？如果绘制的图片超过一屏幕，绘制长图支持吗？

2.绘制一个rect。里面的内容和图片个数都不确定，可以根据内容撑开吗。都必须手动先计算？

3.views的比例都是根据父元素的宽高来处理，那么高度不固定怎么处理?

**Comment by nailuoGG** [comment]
目前我这边使用都是手动计算的
