### ISSUE TITLE
多张海报

### ISSUE THREAD

**Issue by cky5450108** [Kujiale-Mobile/Painter#208]
可以一次生成多张不同的海报吗，放在一个横向的scroll-view里面

**Comment by CPPAlien** [comment]
用一个 painter 绘制多个，得到多个 image 来放到 scroll-view 里面

**Comment by cky5450108** [comment]
我在demo的.wxml文件做了以下修改，card.js里面传的不同的iamgeurl参数，但是都是绘画出同一张图，最后传进去的imageurl参数会覆盖前面的。请问有什么解决办法吗？
<scroll-view  scroll-x="true" bindscroll="scroll" style="width: 100%;white-space: nowrap; display: flex">
  <block wx:for="{{templates}}" wx:key="{{index}}">
  <painter customStyle='position: absolute; left: -9999rpx;' palette="{{template}}" bind:imgOK="onImgOK" widthPixels="1000" />
      <image src="{{image}}" style="width: 654rpx; height: 1000rpx; margin-left:40rpx;" />
  </block>  
  </scroll-view>

**Comment by cky5450108** [comment]
我在demo的.wxml文件做了以下修改，card.js里面传的不同的iamgeurl参数，但是都是绘画出同一张图，最后传进去的imageurl参数会覆盖前面的。请问有什么解决办法吗？
 <scroll-view  scroll-x="true" bindscroll="scroll" style="width: 100%;white-space: nowrap; display: flex">
  <block wx:for="{{templates}}" wx:key="{{index}}">
  <painter customStyle='position: absolute; left: -9999rpx;' palette="{{template}}" bind:imgOK="onImgOK" widthPixels="1000" />
      <image src="{{image}}" style="width: 654rpx; height: 1000rpx; margin-left:40rpx;" />
  </block>  
  </scroll-view>

**Comment by cky5450108** [comment]
请问下如何绘制多个不同的海报，需要创建不同的配置文件吗，我这边只需要替换不同的背景图，其他都是一样的

**Comment by semi-xi** [comment]
我感觉是可以设置painterData之后，然后设置一个flag，如果返回图片生成成功的话就继续条用设置painterData的，这样一直循环，不知道能不能满足你的需要

**Comment by heleicn993** [comment]
可否有示例代码？拿来分享一下谢谢！

**Comment by jacky-xing** [comment]
> 请问下如何绘制多个不同的海报，需要创建不同的配置文件吗，我这边只需要替换不同的背景图，其他都是一样的

不用创建不同的文件吧，只需要传参不一样就行了。之前有个生成商品海报的需求，需要生成一个商品下多张海报（根据商品主图数量决定），我都是用并发的方式生成的，不过有时候会存在画布画的不完整的情况出现。

**Comment by YGragon** [comment]
![image](https://user-images.githubusercontent.com/15891602/94341926-0fec8d80-0040-11eb-8252-fc475faa826e.png)

利用 swiper + swiper-item 生成多张图片，再根据传递的 id=index，最后在返回的图片集合里面通过 splice 拼接图片链接
