### ISSUE TITLE
坐标为负时报错

### ISSUE THREAD

**Issue by wyh888** [Kujiale-Mobile/Painter#22]
当 top、left 等坐标为负时报错，应该是限制了不能用负值，但是实际开发中，有些图片的位置是会超出视图的，比如绘制贴纸功能，是由用户自己拖拽控件进行合成，这时候就会有负坐标的产生。我修改了 painter.js 的 toPx() 的正则验证试了下，发现其实是可以兼容这部分功能。

**Comment by CPPAlien** [comment]
欢迎发 PR 哦

**Comment by CPPAlien** [comment]
负值的支持特性已经加上了，你可以 pull 下最新代码

**Comment by wyh888** [comment]
好的
