### ISSUE TITLE
为什么taro中通过通过id获取不到canvas

### ISSUE THREAD

**Issue by caoliren** [Kujiale-Mobile/Painter#221]
![image](https://user-images.githubusercontent.com/20277781/71581130-d03f5680-2b3e-11ea-89e8-08674f5a3d21.png)
![image](https://user-images.githubusercontent.com/20277781/71581140-d8979180-2b3e-11ea-8ead-c803f21edaa1.png)
已经写了定时器异步了

**Comment by 0JARVIS0** [comment]
canvasToTempFilePath 的 this 是不是没有设为 painter？
