### ISSUE TITLE
真机无法显示自定义字体

### ISSUE THREAD

**Issue by Moon-Future** [Kujiale-Mobile/Painter#223]
引入了自定义字体，在电脑上适用开发者工具生成保存图片，可以正常显示自定义字体，但是IOS真机上就无法显示自定义字体了，直接默认字体，安卓上没测试过，是怎么回事呢

**Comment by JsonSheep** [comment]
微信小程序canvas暂不支持引入外部字体。

**Comment by nailuoGG** [comment]
是微信小程序canvas的限制
