### ISSUE TITLE
绘制图片的URL希望可以支持cloud云开发链接

### ISSUE THREAD

**Issue by ichizi** [Kujiale-Mobile/Painter#233]
![image](https://user-images.githubusercontent.com/7540755/76698450-0f148f80-66de-11ea-8b3c-243c07c05103.png)
如图，
第一个图片是用户头像 https链接。
第二个图片是存在云开发的文件，cloud://，希望能够支持。

**Comment by minchangyong** [comment]
wx.cloud.getTempFileURL({}）
