### ISSUE TITLE
请问有兼容canvas 2d的计划吗？

### ISSUE THREAD

**Issue by thothsun** [Kujiale-Mobile/Painter#238]

**Comment by huxc** [comment]
我也想知道有没有兼容计划 顶一下

**Comment by CPPAlien** [comment]
有的

**Comment by MakerGYT** [comment]
参考[pull](https://github.com/Kujiale-Mobile/Painter/pull/257#issuecomment-658105269)

**Comment by 0JARVIS0** [comment]
painter现已兼容canvas2d，请更新组件获取
