### ISSUE TITLE
mpvue出现无限更新的bug

### ISSUE THREAD

**Issue by HadesMoon** [Kujiale-Mobile/Painter#24]
![image](https://user-images.githubusercontent.com/14729719/43113195-f751c33e-8ebe-11e8-8cc0-bb46bb2f2b8a.png)

当赋值给this.shareImg的时候，发生了无限更新bug，不停的重新绘制。
### painter.js
![image](https://user-images.githubusercontent.com/14729719/43113187-eef4e6d0-8ebe-11e8-98f5-db2ba29e19c1.png)

目前我通过增加判断palette是否有变化来解决这个问题

**Comment by CPPAlien** [comment]
@HadesMoon 脏数据检查已经加到 Painter 中了，你可以pull下最新代码

**Comment by CPPAlien** [comment]
脏数据检查的特性我干掉了，想了一下，觉得还是在外面做判断比较好，Painter 不会检查数据一致就不刷新，因为有时候就是会有强制刷新的需求。

**Comment by charleslo1** [comment]
@CPPAlien 我觉得可以通过 properties 让开发者自定义是否需要脏数据检查，默认可以关闭。因为 mpvue 的开发者还是挺多的，而 mpvue 的这个问题其实已经有很多人提了 issue 了，但官方一直都没修复。如果植入 ``underscore`` 太大，可以考虑植入``lodash/isEqual``

**Comment by CPPAlien** [comment]
目前可以加入 dirty 属性进行脏检查
