### ISSUE TITLE
demo 打开保存图片报错！！！

### ISSUE THREAD

**Issue by jiahuamld** [Kujiale-Mobile/Painter#247]
VM166:1 Uncaught (in promise) thirdScriptError
{"errMsg":"saveImageToPhotosAlbum:fail The \"path\" argument must be of type string. Received type object"}
Object
还有保存为什么格式为pnm?

**Comment by 0JARVIS0** [comment]
你好，demo保存图片报错的问题已解决，保存图片格式问题未能复现。顺带推销一下painter的新功能，现在painter不仅支持生成静态海报，还支持通过点选拖动改变view的位置，可以修改纯文本view的宽度，对图片\色块view进行缩放操作、支持从外部传入对单个view的操作、支持删除单个 view（以上操作皆仅限设置id的view）。这些功能现在都能在demo中体验到，还有更多的玩法，欢迎探索。
