### ISSUE TITLE
使用top填写id来定位，无法准确定位，而left是可以的

### ISSUE THREAD

**Issue by caiyongqiang** [Kujiale-Mobile/Painter#254]
`{
          id: 'head',
          type: 'image',
          url: "https://dss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=3140403455,2984550794&fm=26&gp=0.jpg",
          css: [{
            top: `${footTop + 30}rpx`,
            left: `${footLeft}rpx`,
            width: "160rpx",
            height: "160rpx",
            borderRadius: "50%",
          }],
        },
        {
          type: "text",
          text: "站的对的",
          css: {
            width: '120rpx',
            height: '34rpx',
            fontSize: '30rpx',
            color: 'red',
            top: [`20rpx`, 'head'],
            left: [`20rpx`, 'head'],
          }
        }`
top定位无法像left一样的定位，位置不对；红色文字是根据头像定位来定位，结果跑到上面；
![1f1596c125dbff1f32d4f5946358544](https://user-images.githubusercontent.com/31945098/82721216-b836c200-9ced-11ea-82c2-395dbfc9b3bd.png)

**Comment by SteveWarm** [comment]
top: [20rpx, 'head'] 的意思是： 
20rpx + id为head元素本身高（height）。

你理解的是： 

20rpx +  id为head元素的相对画布的坐标值（top）。

你的理解有误。

**Comment by caiyongqiang** [comment]
> top: [20rpx, 'head'] 的意思是：
> 20rpx + id为head元素本身高（height）。
> 
> 你理解的是：
> 
> 20rpx + id为head元素的相对画布的坐标值（top）。
> 
> 你的理解有误。

明白，那我想问下，我应该传什么参数给组件，可以取消元素的拖拽事件？

**Comment by SteveWarm** [comment]
> > top: [20rpx, 'head'] 的意思是：
> > 20rpx + id为head元素本身高（height）。
> > 你理解的是：
> > 20rpx + id为head元素的相对画布的坐标值（top）。
> > 你的理解有误。
> 
> 明白，那我想问下，我应该传什么参数给组件，可以取消元素的拖拽事件？

没太懂你的意思，可以再开一个增加图片源码说明来讨论

**Comment by minchangyong** [comment]
那如果想 20rpx + id为head元素的相对画布的坐标值（top）。实现这个咋操作呢？
