### ISSUE TITLE
使用网络字体问题

### ISSUE THREAD

**Issue by S1mple199x** [Kujiale-Mobile/Painter#262]
fontFamily应该怎么使用网络字体，在开发者工具上生成一切正常，真机上没有效果

**Comment by 0JARVIS0** [comment]
![WeChatWorkScreenshot_e8c03e26-21e4-4bbe-8ac3-015e1b838bc1](https://user-images.githubusercontent.com/37463753/85497157-0fdb8c80-b610-11ea-8164-af99e0985d55.png)
