### ISSUE TITLE
获取微信网络头像绘制，有时画不上去，排除合法域名配置，应是获取过慢，没画上去，如何确认获取到网络图片再画，而不是延时处理

### ISSUE THREAD

**Issue by 18279493170** [Kujiale-Mobile/Painter#264]
获取微信网络头像绘制，有时画不上去，有时能画上去，已经排除合法域名配置问题，应是获取过慢，在获取到之前就开始绘制了，导致没画上去，如何确认获取到网络图片再画，代码在哪块？而不是延时处理，我看作者在进行绘制之前有300ms的延时，但这样并不能100%保证能全部获取到并绘制上去，如果有做取值校验，具体代码块在哪？望告知！！万谢

**Comment by phpcxy** [comment]
解决了吗，咋关闭了
