### ISSUE TITLE
批量生成 不同地方 使用的海报时，在imgOk里如何区分？能传递自定义参数吗？

### ISSUE THREAD

**Issue by Li-shiwei** [Kujiale-Mobile/Painter#265]
比如:
  1、页面内有 多张 需要动态生成的海报
  2、它们分别放在 A区域  B区域  C区域（会存在页面一打开时，三个区域都要显示出来的情况 且 需要保证它们的先后顺序）
这个时候可以多张同时生成吗？生成后的顺序会变吗？还是必须要  一张一张的等待  同步生成呢？

**Comment by 0JARVIS0** [comment]
目前应该是没有办法做到同时生成三个图片链接的，只能一个一个生成，没生成的用个loading状态顶一下啊，或者是用三个painter分别生成啊。

**Comment by YGragon** [comment]
https://github.com/Kujiale-Mobile/Painter/issues/208

**Comment by lcnphp** [comment]
> 目前应该是没有办法做到同时生成三个图片链接的，只能一个一个生成，没生成的用个loading状态顶一下啊，或者是用三个painter分别生成啊。

同一页面中的 canvas-id 不可重复，如果使用一个已经出现过的 canvas-id，该 canvas 标签对应的画布将被隐藏并不再正常工作
