### ISSUE TITLE
可以实现文档流布局吗？

### ISSUE THREAD

**Issue by Li-shiwei** [Kujiale-Mobile/Painter#267]
动态生成海报时，有多个 文字段落和图片 混排 且 每个文字段落里的文字长度无法固定，导致段落的高度不能定高。
请问用 Painter 可以自动撑开吗？可以实现类似html的文档流布局吗？

**Comment by CPPAlien** [comment]
可以，文字限制宽度，图片可以动态获得文字高度来布局

**Comment by zjydipingxian** [comment]
同问。 有解决方案吗。 在仓库中没找到列子
