### ISSUE TITLE
请问可以支持base64的图片吗

### ISSUE THREAD

**Issue by xiaoxiongzi** [Kujiale-Mobile/Painter#275]
生成携带小程序二维码的海报是挺常见的需求，但是小程序二维码是base64格式的。请问支持base64格式的图片绘制吗，如果不支持，有哪些比较好的方案？

**Comment by 0JARVIS0** [comment]
#270 
可以看下这个pr是否满足要求

**Comment by 0JARVIS0** [comment]
当前painter已经支持base64了，可以直接更新painter获取支持
