### ISSUE TITLE
支不支持图片裁切呢？

### ISSUE THREAD

**Issue by syymo** [Kujiale-Mobile/Painter#277]
支不支持图片裁切呢？
![image](https://user-images.githubusercontent.com/26571594/90308020-709b8d00-df0e-11ea-8d2a-a8b8c0d98719.png)

类似于这种裁切

**Comment by Gitjinfeiyang** [comment]
https://github.com/Gitjinfeiyang/easy-canvas
推荐这个库，支持overflow:hidden效果

**Comment by 0JARVIS0** [comment]
painter支持图片设置scaleToFill和aspectFill两种模式，意义与小程序image标签的mode一致。如果要更为精细的裁剪，比如图片的左上角某块区域，目前painter是不支持的。
