### ISSUE TITLE
能否支持canvas 2d呢？

### ISSUE THREAD

**Issue by shiyuanjieyi** [Kujiale-Mobile/Painter#279]
如题，微信小程序已经很早就更新了canvas2d，但是该插件用的还是旧的canvas api
[微信小程序canvas2d](https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html#Canvas-2D-%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81)

**Comment by 0JARVIS0** [comment]
请参考 #257 该 pr。可以在 heidao 分支获取到支持 canvas2d 的 painter。目前 canvas2d 版的 painter 对动态编辑海报的能力支持仍不完善，如果只需要使用静态生成海报能力的话，可以尝试使用。欢迎在使用当中向我们反馈 canvas2d 版本存在的问题，帮助 painter 变得更完善，也欢迎 pr

**Comment by shiyuanjieyi** [comment]
👌最好整合进master分支，然后引出一个变量是否开启canvas2d，默认可以不开启，如果开启，就关闭动态编辑海报功能
