### ISSUE TITLE
有自定义字体的保存图片还是系统字体

### ISSUE THREAD

**Issue by hqfeijian** [Kujiale-Mobile/Painter#282]
背景：使用自定义字体保存海报
开发工具：模拟器正常显示字体，保存图片的字体也正常。
安卓真机：小程序显示正常，但保存图片中的字体还是系统默认字体
请问有遇到吗？

**Comment by 0JARVIS0** [comment]
https://developers.weixin.qq.com/community/develop/doc/000c26f9cc4f48af2b9aed8e25b000?highLine=canvas%2520%25E5%25AD%2597%25E4%25BD%2593
