### ISSUE TITLE
推荐下这个库哈 🐶，欢迎交流

### ISSUE THREAD

**Issue by Gitjinfeiyang** [Kujiale-Mobile/Painter#284]
https://github.com/Gitjinfeiyang/easy-canvas

支持文档流，功能强大
兼容小程序以及web，无第三方依赖
支持组件化，全局组件以及局部组件
支持事件
高性能，scroll-view支持脏矩形，只绘制可视部分
支持操作element，类似操作dom修改文档流
图片缓存

**Comment by aetherwu** [comment]
特别困惑，这个到底是拿来做什么的呢？
