### ISSUE TITLE
微信开发者工具上选真机调试出错，但是走开发版和体验版均OK

### ISSUE THREAD

**Issue by vrworking** [Kujiale-Mobile/Painter#289]
微信开发者工具上选真机调试出错，但是走开发版和体验版均OK，是不是只有我这边奇葩？😭

真机调试走到注册 app.json 定义的页面之前有一个报错：
```
runtime.js:1 Error: module "src/components/painter/lib/pen.js" is not defined
```

然后进入要制作海报的界面，生成海报时拿不到临时文件导致一堆报错：
```
painter.js:724 getImageInfo  failed, {"errMsg":"getImageInfo:fail image not found"}
The size: NaNpx is illegal
The size: NaNpx is illegal
The size: NaNpx is illegal
The size: NaNpx is illegal
The size: NaNpx is illegal
```

下面的非法 size 是因为 getImageInfo 走到 fail 导致后续操作都失败，最终导致无法生成海报。

but

我走开发版和体验版的真机却所有功能都正常 😓😓

> PS: 给插件打上 version 或者 release 吧，发 issue 时可以报上具体的版本。

**Comment by 0JARVIS0** [comment]
目前这个问题还是能稳定复现吗？我们这里无法复现……
