### ISSUE TITLE
dancePalette 使用这个动态模板好像不会走bind:ImgOk这个方法

### ISSUE THREAD

**Issue by SmallSmallrui** [Kujiale-Mobile/Painter#296]

**Comment by neatstudio** [comment]
我也发现了。。。。

**Comment by neatstudio** [comment]
生成是生成了。但imgOK没有触发，导致没有 e.detail.path 生成

**Comment by neatstudio** [comment]
看了一下源码。再对了一下文档。应该用：

didShow ：动态模版，绘制结束时触发
--

**Comment by neatstudio** [comment]
didShow也没有办法获取 image.path...这个就很尴尬了

**Comment by neatstudio** [comment]
@SmallSmallrui 先v-if隐藏组件。然后赋完值后，再显示。这时候就可以用palette的静态组件了。这时候也就可以触发 ImgOK事件了。

我现在就是这样解决的

**Comment by peachapp** [comment]
> @SmallSmallrui 先v-if隐藏组件。然后赋完值后，再显示。这时候就可以用palette的静态组件了。这时候也就可以触发 ImgOK事件了。
> 
> 我现在就是这样解决的
你好有代码可以看一下嘛 我试了一下好像没用欸

**Comment by 0JARVIS0** [comment]
由于动态模版进行了分层操作，所以绘制并不是在一个canvas上的，即使通过imgok传递出来的路径也是错误的。需要生成正确的图片还是需要使用静态模版

**Comment by 0JARVIS0** [comment]
https://developers.weixin.qq.com/community/develop/article/doc/0004ce04bfc07813744c89abe51013
