### ISSUE TITLE
建议 增加传入回调的方法 

### ISSUE THREAD

**Issue by lzd358194530** [Kujiale-Mobile/Painter#298]
这个实现应该好实现 
我在点击分享的时候想生成分享图上传到服务器 拿到图片再分享

**Comment by neatstudio** [comment]
ImgOK ，在这个事件里处理啊

**Comment by lzd358194530** [comment]
> ImgOK ，在这个事件里处理啊

onShareAppMessage 需要在这里 createPoster 然后 分享

**Comment by neatstudio** [comment]
你可以开个异步处理好。只是不显示。。在onShareAppMessage的时候，直接拿数据啊

**Comment by lzd358194530** [comment]
目前确实是这样处理的
