### ISSUE TITLE
image的mode属性如何设置？

### ISSUE THREAD

**Issue by shuimupj** [Kujiale-Mobile/Painter#30]
{
          type: 'image',
          url: '/images/icon_recruit-bg.jpg',
          css: {
            mode: 'aspectFill',
            top: '0rpx',
            left: '0rpx',
            width: '750rpx',
            height: '750rpx',
          },
},
文档说mode是image的自有css，是这样写吗？

**Comment by shuimupj** [comment]
我这边设置了，不可以，图片还是原来的样子，没有占满我设置的尺寸，感觉还是aspectFit的样子
（不好意思，不知道什么原因我的issue上传不了图片）

**Comment by shuimupj** [comment]
**经过测试发现，mode的两个值反了**，mode的默认值是_aspectFill_不是_aspectFit_，且
aspectFit：对应小程序imge组件的aspectFill（不保持纵横比缩放图片，使图片的宽高完全拉伸至填满 image 元素）
aspectFill：对应小程序imge组件的aspectFit（保持纵横比缩放图片，使图片的长边能完全显示出来。也就是说，可以完整地将图片显示出来。）

**Comment by CPPAlien** [comment]
对，我readme 写反了 囧，默认是 aspectFill。aspectFit 就是对应小程序的 aspectFit，Fill 就是对应Fill 的

**Comment by CPPAlien** [comment]
@shuimupj 请 pull 下最新代码，和阅读下 readme，目前 mode 属性实现有更新，默认为 aspectFill，可以使用 scaleToFill，当未设置 height 和 width 时，图片会自动显示原大小
