### ISSUE TITLE
微信小程序canvas 2d 接口目前不支持

### ISSUE THREAD

**Issue by jsonLiao** [Kujiale-Mobile/Painter#306]
canvas 2d 接口支持同层渲染且性能更佳，建议切换使用

**Comment by 0JARVIS0** [comment]
painter 已支持 canvas2d 接口哦，文档中有切换至 canvas2d 接口的方式，可以仔细读一下。可以在示例中直接尝试使用 canvas2d 也可以在 paintercore 的 canvas2d 分支获取到组件。

**Comment by jsonLiao** [comment]
![1](https://user-images.githubusercontent.com/31090779/100566496-2d202f80-3301-11eb-9117-a7996ed63d4e.png)
我试了一下 报这个 图片出不来

**Comment by TongChen-10** [comment]
@jsonLiao 请问这个问题您解决了么？

**Comment by jsonLiao** [comment]
> @jsonLiao 请问这个问题您解决了么？

我现在的处理方式是针对不支持的手机做兼容处理，就是不支持的手机不开启2D.
