### ISSUE TITLE
在 iPhone XR 真机下，海报图会出现整体下移的问题

### ISSUE THREAD

**Issue by Chorer** [Kujiale-Mobile/Painter#307]
在 iPhone XR 真机下绘制海报，会出现海报整体下移的问题：比如文字原本 top 是0，刚好在海报顶部，但实际在真机上，文字的 top 大概有几十 rpx，导致顶部出现空白，而底部显示不全。如下图：
![Snipaste_2020-11-14_22-18-47](https://user-images.githubusercontent.com/43442630/99149178-646acb80-26c7-11eb-9836-e702b8792488.png)

不管是展示还是保存下来的图片，都有这个问题。目前只在 IPhone XR 真机下发现该问题，其它机型正常，并且模拟器中，iPhone XR 的表现也是正常的。排查了很久也没找到问题所在，不知道是否可以帮忙看下这个问题？

**Comment by jobn123** [comment]
你使用rpx替换px试试

**Comment by Chorer** [comment]
> 你使用rpx替换px试试

我一直用的是 rpx。已经放弃这个方案了，官方应该也没空管这个 issue，待会我 close 掉。
