### ISSUE TITLE
action具体要如何使用？

### ISSUE THREAD

**Issue by ELBUND** [Kujiale-Mobile/Painter#308]
文档中关于action的用法有点少欸...我在使用的过程中，action传入后，画布上的实时改了，但是没有触发imgOK方法，导致了生成的图片还是没修改前的图片，请教下各位大佬

**Comment by 0JARVIS0** [comment]
https://developers.weixin.qq.com/community/develop/article/doc/0004ce04bfc07813744c89abe51013

**Comment by ELBUND** [comment]
> https://developers.weixin.qq.com/community/develop/article/doc/0004ce04bfc07813744c89abe51013

感谢指引，清楚其用法了
