### ISSUE TITLE
文字换行 加 文字带上背景颜色 加 换行中间缝隙

### ISSUE THREAD

**Issue by JiaLuo** [Kujiale-Mobile/Painter#313]
假如三行文字，每行文字都有黑色背景，但是每行与每行之间都有一个背景图的颜色，而不是文字的背景颜色。怎么实现啊？

**Comment by 0JARVIS0** [comment]
那就分三个text写啊～～

**Comment by JiaLuo** [comment]
这个文字是动态的，用户输入的。我现在的做饭就是每行13个字，然后做切割。


在 2020年12月11日 11:54，0JARVIS0<notifications@github.com> 写道：


那就分三个text写啊～～
