### ISSUE TITLE
设置文本的fontWeight属性问题

### ISSUE THREAD

**Issue by panzhongyue** [Kujiale-Mobile/Painter#315]
fontWeight属性加粗（bold）字体，在微信开发者工具里面显示加粗正常，但是真机测试没有加粗显示，分布测试了iPhone 6s plus 和 小米 4c的手机，都没有正常显示粗体?

**Comment by CPPAlien** [comment]
https://github.com/Kujiale-Mobile/Painter/commit/fc47556fea24fd62c9aee85f6b2eab5c79cde50e
