### ISSUE TITLE
在新版开发者工具1.05.2102010中，保存出现saveImageToPhotosAlbum:fail auth deny错误

### ISSUE THREAD

**Issue by mean-liang** [Kujiale-Mobile/Painter#334]
Error: MiniProgramError
{"errMsg":"saveImageToPhotosAlbum:fail auth deny"}

**Comment by EricYangXD** [comment]
重新获取一遍授权不行吗？

**Comment by 0JARVIS0** [comment]
这是微信授权获取出错，不是painter这里的报错，可以看下是不是之前拒绝授权了
