### ISSUE TITLE
生产二维码功能不支持在二维码中设置logo

### ISSUE THREAD

**Issue by fshmjl** [Kujiale-Mobile/Painter#340]
![image](https://user-images.githubusercontent.com/8537658/121651880-ac22cb80-cacd-11eb-8267-5c49935c953f.png)
如这种效果，目前好像不支持，只支持存二维码（即无logo情况）

**Comment by CPPAlien** [comment]
2.2.0 可以使用 calc 实现这个效果
{
          id: 'one',
          type: 'qrcode',
          content: '12345',
          css: {
            width: '400rpx',
            left: '50%',
            align: 'center',
            top: '30rpx',
            height: '400rpx',
          },
        },
        {
          id: 'two',
          type: 'image',
          url: '/palette/avatar.jpg',
          css: {
            width: '100rpx',
            left: 'calc(one.left)',
            align: 'center',
            top: 'calc(one.top + one.height / 2 - 50rpx)',
            height: '100rpx',
            borderRadius: '10rpx',
            borderWidth: '10rpx',
            borderColor: '#fff'
          },
        },
