### ISSUE TITLE
引入组件后报错

### ISSUE THREAD

**Issue by xianqiangzhao** [Kujiale-Mobile/Painter#343]
Error: Component is not found in path "components/painter/painter" (using by "Userpackage/recruitDetail/recruitDetail")
    at e (VM3577 WAService.js:2)

在用到的页面 
  {
  "usingComponents":{
    "painter":"../../../components/painter/painter"
}
}
components 目录在根目录，编译OK，进入使用的页面就报错。
谢谢！

**Comment by 0JARVIS0** [comment]
请问是使用了原生开发还是taro或是其他框架？
原生请参考 https://github.com/Kujiale-Mobile/Painter/blob/master/pages/example/example.json
taro请直接使用npm包，我们为taro2/3都提供了封装好的组件
taro2: npm i mina-painter
taro3: npm i painter-taro-3
如果是其他框架，请指明一下

**Comment by xianqiangzhao** [comment]
我用的是原生的，参考了您给的文件了，还是报错。抱歉，放弃了。

**Comment by 0JARVIS0** [comment]
painter的这个demo有拉下来跑过吗？跑的起来吗？要不尝试加一下微信，备注下painter，我拉你进讨论群，方便交流？
![ea652f8e31b536681c233bf148e9736d](https://user-images.githubusercontent.com/37463753/123946551-eba84d80-d9d1-11eb-8ca1-5d55686a0858.png)
