### ISSUE TITLE
一个页面多个painter 会绘制错误

### ISSUE THREAD

**Issue by Silence108** [Kujiale-Mobile/Painter#354]
一个页面多个painter 会绘制错误 这个怎么解决

**Comment by 0JARVIS0** [comment]
![企业微信截图_7362cc8e-a525-43f5-88ef-c67f05f0e59a](https://user-images.githubusercontent.com/37463753/127249574-443fd567-a077-43bd-b874-8e9f093d2f60.png)
painter 内部使用了canvas组件，受到相应规则限制

**Comment by Silence108** [comment]
> ![企业微信截图_7362cc8e-a525-43f5-88ef-c67f05f0e59a](https://user-images.githubusercontent.com/37463753/127249574-443fd567-a077-43bd-b874-8e9f093d2f60.png)
> 画家内部使用了画布组件，受到了相应的限制

这个不可以修改id不同吗

**Comment by 0JARVIS0** [comment]
可以啊，如果你是用的原生组件，可以对painter做相应改造，如果是用的taro的包可能就不行了

**Comment by Silence108** [comment]
好的 明白了 谢谢亲
