### ISSUE TITLE
The size: undefined is illegal

### ISSUE THREAD

**Issue by chuyun** [Kujiale-Mobile/Painter#356]
一直会出现The size: undefined is illegal的报错，直接看mina-painter的demo就可以

**Comment by 0JARVIS0** [comment]
你用的模版可以发一下吗？应该是模版写的有点问题

**Comment by chuyun** [comment]
> 你用的模版可以发一下吗？应该是模版写的有点问题

Demo就可以 https://github.com/Kujiale-Mobile/Taro-Painter-Demo

**Comment by 0JARVIS0** [comment]
嗯这是样例写的有些问题，会更新下
