### ISSUE TITLE
网络图片空白

### ISSUE THREAD

**Issue by liuxuerong** [Kujiale-Mobile/Painter#357]
taro2.x生成的小程序 android在开发和体验版使用网络图片都显示正常 但是正式版图片空白 ；ios在开发版正常 体验版和线上会显示空白
开发的样子：
![image](https://user-images.githubusercontent.com/29587842/129827700-fbf379cc-f9f6-41b5-95e2-7fae93425588.png)
发布后：
![5597d09957b4372a1e5941264a4784a](https://user-images.githubusercontent.com/29587842/129827818-b77e0d00-be9f-4835-a0c6-dab97165dab7.jpg)

**Comment by 1061127386** [comment]
网络图片需要在小程序后台 配置downloadFile合法域名

**Comment by liuxuerong** [comment]
![image](https://user-images.githubusercontent.com/29587842/129830881-37795805-bf9b-43d6-9a2e-e49a496e6238.png)
我确认了是已经配置的
![image](https://user-images.githubusercontent.com/29587842/129831027-2514189e-c67a-4f12-85ef-9e2ad31ec01d.png)

**Comment by liuxuerong** [comment]
非常感谢 ，是您说的问题。后台返回的路径中的域名没有配置

**Comment by liuxuerong** [comment]
非常感谢 ，是您说的问题。后台返回的路径中的域名没有配置
