### ISSUE TITLE
使用calc函数直接报错

### ISSUE THREAD

**Issue by 13597843021** [Kujiale-Mobile/Painter#363]
The size: calc(three.bottom + 10rpx) is illegal
直接复制你的案例到小程序直接报错

**Comment by 0JARVIS0** [comment]
报错信息有吗？painter组件有更新过吗？

**Comment by Wangxq0614** [comment]
> The size: calc(three.bottom + 10rpx) is wrong 直接
> 复制你的案例到小程序直接报错

重新下载一下最新版本，亲测可用。因为我遇到过相同问题 - 2021/09/15
