### ISSUE TITLE
为什么用 -9999rpx for top, left?

### ISSUE THREAD

**Issue by ee01** [Kujiale-Mobile/Painter#365]
<canvas canvas-id="photo" style="{{photoStyle}};position: absolute; left: -9999px; top: -9999rpx;" />

我去除掉负值，就可以正常显示了，为什么这里要用负值？

**Comment by ee01** [comment]
或者带参数use2D 就正常显示了。我看到源码2d没有负值top left

**Comment by 0JARVIS0** [comment]
历史问题。最开始painter是想作为一个离屏渲染的工具的，生成的图片用image组件展示，所以style写-9999的目的就是为了让painter不出现在屏幕中。不过如果有需求，可以改一下组件，让painter显示在页面中就是了。

**Comment by ee01** [comment]
了解～
