### ISSUE TITLE
文字中有表情怎么办

### ISSUE THREAD

**Issue by Traveller957** [Kujiale-Mobile/Painter#366]
emoji算作两个字符，换行时被拆开安卓就识别成乱码了，ios还会造成死循环，可能是因为ios识别不了的变成空，宽度就没有变化

**Comment by 0JARVIS0** [comment]
是用的原生组件吗？是的话更新下组件，最新合的pr就是解决这个问题的

**Comment by Traveller957** [comment]
> 是用的原生组件吗？是的话更新下组件，最新合的pr就是解决这个问题的

我看了那个还是有问题，首次平均分开的时候表情还是被当做两个字符串处理，第一行末尾还是可能会出现乱码

**Comment by CPPAlien** [comment]
#355 967c84df91c7b0a4b9272cd3a56a1f740a281823
