### ISSUE TITLE
有办法让palette最外层容器的高度根据子View自动调整吗

### ISSUE THREAD

**Issue by binzhihao** [Kujiale-Mobile/Painter#38]
如题，我从上一个页面传递一段文字过来，因为文字长短不一，不能把palette的高度写死。有办法吗？我没试出来。

**Comment by binzhihao** [comment]
解决了，根据行高等计算高度就行了

**Comment by CPPAlien** [comment]
@binzhihao 因为我这边采用 absolute 布局，外层根据子 view 来动态计算不太好做。能具体分享下你的做法吗？

**Comment by binzhihao** [comment]
我是这么做的：容器的宽度写死（比如：652rpx），然后跟据文字大小（比如：30rpx）计算一行大概能容纳多少字，结合文字长度就可以计算出大概需要多少行；再然后根据行高计算文字区域需要的总高度，作为一个参数，在palette初始化的时候传递进去，palette将这个参数设置为高度即可。虽然因为中英混排数字混排等可能有少许计算误差，但是实践中末尾预留一到两行的空间就几乎没有什么问题。
没有改动源码，只是改了一下使用方式。
