### ISSUE TITLE
文字不能两端对齐（justify）多行文本看着比较难受

### ISSUE THREAD

**Issue by binzhihao** [Kujiale-Mobile/Painter#39]
有啥方法吗？

**Comment by CPPAlien** [comment]
这个和字体本身有关，无法两边都完美对齐的，你只能选择左或者右来对齐。

**Comment by sdz123** [comment]
> 这个和字体本身有关，无法两边都完美对齐的，你只能选择左或者右来对齐。

和字体没啥关系，根本原因是微信小程序这个平台的画布中，文字的textAlign属性不支持设置“justify”属性。
https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/extended/component-plus/wxml-to-canvas.html
