### ISSUE TITLE
可以获取绘制的文字内容的高度吗？

### ISSUE THREAD

**Issue by Joyee** [Kujiale-Mobile/Painter#45]

**Comment by CPPAlien** [comment]
不可以，你可以直接用你设置的高度，或者 text，多行，就乘以多个。虽不够精确。

**Comment by fly-sheep** [comment]
> 不可以，你可以直接用你设置的高度，或者 text，多行，就乘以多个。虽不够精确。

目前已经支持id的模式去动态设置偏移量，但只支持left、right、top；但为什么不考虑把width、height属性也支持id这种模式呢？

**Comment by weiTimes** [comment]
我也觉得，或者可以把动态设置偏移量的方法给暴露出来
