### ISSUE TITLE
是否考虑支持文字竖直排列？

### ISSUE THREAD

**Issue by inooNgt** [Kujiale-Mobile/Painter#48]
CSS中writing-mode可以改变文档流的方向，Painter考虑增加此功能吗

**Comment by CPPAlien** [comment]
可以考虑

**Comment by CPPAlien** [comment]
文字竖排，你可以通过向每个文字之间插入 换行符来实现

**Comment by CPPAlien** [comment]
![](https://user-images.githubusercontent.com/4279515/61357471-f16efc00-a8aa-11e9-84b3-192fe158f38d.png)
