### ISSUE TITLE
小程序跳转现在限制10个 这个项目要火了

### ISSUE THREAD

**Issue by icksky** [Kujiale-Mobile/Painter#51]

**Comment by CPPAlien** [comment]
怎么说？

**Comment by icksky** [comment]
> 怎么说？

@CPPAlien 盒子类的小程序现在无法自由跳转, 限制成10个了. 那后续只能用二维码跳转的方式了. 这个时候 Painter 生成跳转图片就大有用处了

**Comment by CPPAlien** [comment]
二维码方式需要对方 APP 设置了普通二维码打开方式，而且还要这边生成了对应二维码后，把图片保存再发到微信中，然后让用户长按才能跳转，感觉挺麻烦的

**Comment by icksky** [comment]
@CPPAlien 我所说的是小程序跳转到其他小程序或者其他小游戏, 不是 APP

**Comment by CPPAlien** [comment]
对写错了，我说的就是小程序或者小游戏
