### ISSUE TITLE
增加小程序码判断机制

### ISSUE THREAD

**Issue by log6262635** [Kujiale-Mobile/Painter#54]
有个疑问，档使用官方提供的小程序码生成时，由于每次生成的小程序的临时文件地址不一样，这样的话岂不是每次都要缓存，这样的话，缓存空间被占用的很快，还是我理解有误

**Comment by log6262635** [comment]
还有就是里面的qrcode类型与image类型的区别体现在那里？缓存机制不同？

**Comment by CPPAlien** [comment]
qrcode 可以直接生成普通二维码，image 只是图片展示，缓存有 LRU 机制，没事的
