### ISSUE TITLE
文字行数不确定的情况如何实现高度自适应和排版

### ISSUE THREAD

**Issue by houyanchao** [Kujiale-Mobile/Painter#55]
如下图所示，奖项和抽奖说明的文字个数都是不确定的，如何实现这种布局？

![wechatimg98](https://user-images.githubusercontent.com/9604104/47511610-2cf51080-d8ad-11e8-9b4e-2dae3bff7eb2.jpeg)

**Comment by lihuangshuaige** [comment]
canvas  高度是死的

**Comment by CPPAlien** [comment]
你也可以计算得来呀

**Comment by CPPAlien** [comment]
都是 json in js 的方式，高度是多少，你可以自己写套适合自己的规则就行
