### ISSUE TITLE
加入表情之后，苹果系统的绘制会错位。

### ISSUE THREAD

**Issue by yaojaa** [Kujiale-Mobile/Painter#56]
一段文字 里面包含😊这样的输入法表情。。
然后悲剧错乱了

**Comment by CPPAlien** [comment]
麻烦截个图看下

**Comment by yaojaa** [comment]
> 麻烦截个图看下
![wechatimg312](https://user-images.githubusercontent.com/1989050/47627222-cd775900-db69-11e8-979c-017cc9bcca67.jpeg)

- 
当文本内容区有表情和换行的时候。安卓手机直接过滤了 不显示表情和换行。
苹果手机 有换行，表情也会显示，但会错乱。

**Comment by yaojaa** [comment]
另外手动换行和自动换行，显示的行高不一样。

**Comment by yaojaa** [comment]
也就是说line-height的设置，对于文本框 中的手动换行是无效的。

**Comment by yaojaa** [comment]
而且对于文本框 中的手动换行的 情况。maxlines也是无效的。我设置maxlines 8行。结果出来了全部。

**Comment by CPPAlien** [comment]
目前 Painter 不支持手动换行，这个特性在 to-do 里面，后续会完善
