### ISSUE TITLE
真机调试报错

### ISSUE THREAD

**Issue by BellaAngel** [Kujiale-Mobile/Painter#58]
Error: file: static/canvasdrawer/canvasdrawer.js
unknown: Unexpected token (92:12)
90 | this.drawImage({
91 | ...views[i],
> 92 | url: tempFileList[imageIndex]
| ^
93 | })
94 | imageIndex++
95 | } else if (views[i].type === 'text') {

**Comment by CPPAlien** [comment]
这代码是你自己写的吧
