### ISSUE TITLE
canvasToTempFilePath failed, {"errMsg":"canvasToTempFilePath: fail canvas is empty"}

### ISSUE THREAD

**Issue by jserlin** [Kujiale-Mobile/Painter#60]
mpvue项目点列表进入需要绘制的详情，未绘绘制完，点返回 错误
canvasToTempFilePath failed, {"errMsg":"canvasToTempFilePath: fail canvas is empty"}

**Comment by CPPAlien** [comment]
请提到 https://github.com/Kujiale-Mobile/Mpvue-Painter-Demo 中
