### ISSUE TITLE
mpvue 制作海报

### ISSUE THREAD

**Issue by zhangkaicheng521** [Kujiale-Mobile/Painter#61]
真机测试的时候，微信的头像，没有画到画布上。在开发者工具上可以，请问这是什么缘故

**Comment by CPPAlien** [comment]
图片绘制到画布上需要下载，而下载的图片的地址域名需要在白名单里面

**Comment by zhangkaicheng521** [comment]
> 图片绘制到画布上需要下载，而下载的图片的地址域名需要在白名单里面

那就是说，只要我把 微信头像的这个域名，配置到  白名单 里就可以了吧

**Comment by CPPAlien** [comment]
嗯，在后台放到 download 白名单中
