### ISSUE TITLE
小程序打开调试模式或者真机调试下，网络加载的图片显示，普通模式下，不显示图片

### ISSUE THREAD

**Issue by woshilaoge** [Kujiale-Mobile/Painter#62]
![image](https://user-images.githubusercontent.com/22810511/48185468-084e6d80-e370-11e8-8a93-61abf70a5417.png)
![image](https://user-images.githubusercontent.com/22810511/48185475-0d132180-e370-11e8-95b9-8671293e1a86.png)

![image](https://user-images.githubusercontent.com/22810511/48185569-5c595200-e370-11e8-9cd8-5f3d1a29a475.png)

如上图，开发者工具上是显示好的，
但是 手机上预览就不显示图片，打开调试模式后，显示图片。ios 安卓都已测试，同样问题

**Comment by CPPAlien** [comment]
https://github.com/Kujiale-Mobile/Painter/issues/61

**Comment by woshilaoge** [comment]
好的， 感谢
