### ISSUE TITLE
字体排版比较特殊，可以提供一个回调方法重载画布定位

### ISSUE THREAD

**Issue by icai** [Kujiale-Mobile/Painter#69]
比如有些需求，需要根据行数进行定位
<img width="321" alt="spec_export_-_sketch_measure_2_4" src="https://user-images.githubusercontent.com/1061012/49371981-22435c00-f734-11e8-9a5f-ed0a554e4663.png">
<img width="272" alt="spec_export_-_sketch_measure_2_42" src="https://user-images.githubusercontent.com/1061012/49371989-2a9b9700-f734-11e8-91ef-839ce7f0003f.png">

**Comment by CPPAlien** [comment]
目前还做不到

**Comment by 844189873** [comment]
我也遇到同样的问题，后面的view需要跟据前一个view的行数据来定位，这个怎么解决的呢？

**Comment by icai** [comment]
@844189873 自己在component预留一个空的回调方法，然后在instance  overwrite 该方法
