### ISSUE TITLE
如何接入mpvue

### ISSUE THREAD

**Issue by sideFlower** [Kujiale-Mobile/Painter#71]

**Comment by CPPAlien** [comment]
见readme，其中有说方法

**Comment by well-monkey** [comment]
mpvue 里面 第二步的引入 应该放到main.json中
2. 引入组件
在需要使用 Painter 的页面的 main.js 中加入 'painter': '/static/painter/painter'

import Vue from 'vue'
import App from './index'
const app = new Vue(App)
app.$mount()
export default {
 config: {
   navigationBarTitleText: 'demo',
   usingComponents: {
     'painter': '/static/painter/painter'
   }
 }
}
