### ISSUE TITLE
返回的图片无法在真机中显示

### ISSUE THREAD

**Issue by git-lt** [Kujiale-Mobile/Painter#76]
onImgOk 返回 的图片地址：
![image](https://user-images.githubusercontent.com/8443758/50287647-52159200-049e-11e9-9ca0-1acb63e1d0c0.png)

真机中 以 wxfile 开头的图片，无论是 赋给 image 的 src， 还是做为背景图片都无法显示，只能调用预览图片api查看图片 wx.previewImage({ urls: [url] })

请问我要怎样才能直接给 image 显示呢？

**Comment by CPPAlien** [comment]
直接用 src 就可以显示的
