### ISSUE TITLE
设置align:'center'没有居中

### ISSUE THREAD

**Issue by DengRiGuang** [Kujiale-Mobile/Painter#77]
item:{
      width: '355px',
      height: '519px',
      borderRadius: '20px',
      background: '../temp/small_static/57_min.jpg',
      views:[
        {
          type:'image',
          url:'../uploads/20181212/ce67976845779da30ede713d965e6a8b.jpg',
          css: {
            align:'center',
            top: '50px',
            width: '70px',
            height: '70px',
            borderRadius: '35px',
            borderColor:'white',
            borderWidth:'2rpx'
          }
        },
        {
          type:'text',
          text: "光",
          css:{
            align: 'center',
            top: '140rpx'
            left: '140rpx'
          }
        }
      ]
    }

**Comment by CPPAlien** [comment]
请咨询阅读readme，align 并不是给居中用的，align 是一种对齐策略
