### ISSUE TITLE
安卓手机有bug，绘制的图片永远是第一次进来缓存的文件

### ISSUE THREAD

**Issue by dajunzhu** [Kujiale-Mobile/Painter#78]
安卓手机有bug，绘制的图片永远是第一次进来缓存的文件

**Comment by dajunzhu** [comment]
> 安卓手机有bug，绘制的图片永远是第一次进来缓存的文件

**Comment by DengRiGuang** [comment]
我这边也遇到了，安卓有些手机会，苹果不会，最后找到问题，是微信文件缓存文件一直读取上一个图片无法进行覆盖，我尝试去删除缓存数据不生效，我就在生成图片时加入时间戳就没出现过了。

**Comment by xiaoshuoyiyi** [comment]
页面销毁时，清除所有数据就好了！
