### ISSUE TITLE
图片尺寸过大，在安卓上面会显示绘制不全

### ISSUE THREAD

**Issue by semi-xi** [Kujiale-Mobile/Painter#79]
```js
let view = { // 商品图片
        type: 'https://yjmf.bs2dl-ssl.yy.com/yym101ip_1812494692_1545978168_1155215852.jpg',
        url: productPic,
        css: {
          width: '630rpx',
          height: '630rpx',
          borderRadius: '20rpx',
          top: '225rpx',
          left: '375rpx',
          align: 'center'
        }
      }
```
原因是调用的是
`this.ctx.drawImage(view.url, startX, startY, rWidth, rHeight, -(width / 2), -(height / 2), width, height);`
如果调用`this.ctx.drawImage(view.url, -(width / 2), -(height / 2), width, height)` 就没问题，这样的话有点迷

看过官方有说过是图片尺寸过大的话就会出现绘制补全的问题，不知道有没有解决办法呢。还是说直接用下面的那个

**Comment by CPPAlien** [comment]
下面那个没法做图片显示策略
