### ISSUE TITLE
view用了borderRadius这个属性就会生成一条边框

### ISSUE THREAD

**Issue by jmy08** [Kujiale-Mobile/Painter#8]
用了圆角属性填充颜色都会有一条黑色边框

**Comment by CPPAlien** [comment]
请用最新代码，目前在 Android 的某些机型上确实会出现这种情况

**Comment by jmy08** [comment]
已经用了最新的代码，在微信开发者工具以及ios都有这种情况-。-而且生成的二维码有时候会糊掉 无法识别

**Comment by CPPAlien** [comment]
额，能截图看下么

**Comment by jmy08** [comment]
![](http://kl-widget.b0.upaiyun.com/go-v0.1/demo.png)

**Comment by CPPAlien** [comment]
这个 demo 挺老了，最新版已经解决了，你 git pull origin master 一下吧

**Comment by jmy08** [comment]
好的 非常感谢你
