### ISSUE TITLE
合成图片过慢

### ISSUE THREAD

**Issue by dgburn** [Kujiale-Mobile/Painter#80]
代码中在生成图片时用了300ms的延迟, 实际上直接生成图片失败的概率并不大, 所以建议这样修改,
在wx.canvasToTempFilePath的fail回调中去延迟300ms再做一次重试
(请忽略eslint的校验)
![image](https://user-images.githubusercontent.com/22960370/50594622-43849d00-0ed8-11e9-8242-97930c52beec.png)

**Comment by CPPAlien** [comment]
不单是生成失败的问题，有可能会导致图片生成的有问题，以前版本是很大概率会出错的，有可能微信后续版本改进了

**Comment by dgburn** [comment]
嗯, 现在确实没怎么遇到过生成有问题的了
