### ISSUE TITLE
建议将LRU做成可配置的, 因为有时这并非必须的

### ISSUE THREAD

**Issue by dgburn** [Kujiale-Mobile/Painter#81]

**Comment by log6262635** [comment]
这个特性现在支持了吗

**Comment by CPPAlien** [comment]
目前你可以在 app.js 配置一个 PAINTER_MAX_LRU_SPACE = xx 来设置 LRU 区域的大小，建议设置成 1 后，就等于 不会进行 LRU 了

**Comment by xiaoshuoyiyi** [comment]
是啊，数据有时会实时更新，然而canvas绘制的数据却不会更新！很苦恼！
