### ISSUE TITLE
在mpvue项目中无法使用，求助。

### ISSUE THREAD

**Issue by mrlizonglin** [Kujiale-Mobile/Painter#83]
![image](https://user-images.githubusercontent.com/22819077/50830119-c21e8600-1381-11e9-9e47-91da1a3fc39e.png)

![image](https://user-images.githubusercontent.com/22819077/50830141-d82c4680-1381-11e9-90ff-191da922d1df.png)

**Comment by CPPAlien** [comment]
请看 readme 中的有关说明，里面有例子

**Comment by mrlizonglin** [comment]
@CPPAlien  你好，我是有参考那个例子的，但是还是渲染不出来，代码如截图，能麻烦指导一下吗？

**Comment by shuliuzhenhua** [comment]
@mrlizonglin 可以参考这个 https://github.com/Kujiale-Mobile/Painter/pull/106

**Comment by mrlizonglin** [comment]
@shuliuzhenhua 感谢回复，由于时间跨度过长，已经放弃使用这个啦~

**Comment by shuliuzhenhua** [comment]
@mrlizonglin  哈哈，好吧。真好

**Comment by well-monkey** [comment]
mpvue 里面 第二步的引入 应该放到main.json中
2. 引入组件
在需要使用 Painter 的页面的 main.js 中加入 'painter': '/static/painter/painter'
```
import Vue from 'vue'
import App from './index'
const app = new Vue(App)
app.$mount()
export default {
 config: {
   navigationBarTitleText: 'demo',
   usingComponents: {
     'painter': '/static/painter/painter'
   }
 }
}
```


而是直接在main.json中放入
```
 "usingComponents": {
    "painter": "/static/painter/painter"
  }
```

**Comment by mixsun** [comment]
修复的这个版本还是不能使用

**Comment by bestK** [comment]
一样的问题 `onImgOk` 不触发
