### ISSUE TITLE
一直停在海报生成中，无法点击，怎么解决(网络差的环境下)

### ISSUE THREAD

**Issue by DengRiGuang** [Kujiale-Mobile/Painter#84]
// 获取小程序二维码
  async getQrcodeCode() {
    let that = this;
    let token = wepy.getStorageSync('userToken');
    // path后不能带参数 在scene带上
    const create_code = await api.createQRcode(
      {
        path: 'pages/preview',
        scene:this.wordId+','+this.wordUrl+','+'1',
        post_id: this.wordId,
        width: 400,
        is_hyaline: true,
        auto_color: false,
        line_color: '{"r":"0","g":"0","b":"0"}'
      },
      token
    );
    if (create_code.code == 1) {
      this.item.views[4].url = await base64src(
        'data:image/jpg;base64,' + create_code.data.qr
      );
      this.isShowText = true;
      this.shareImage = create_code.data.p.sc;
      this.item.background = create_code.data.p.s;
      this.item.views[0].url = create_code.data.p.g;
      this.item.views[1].text = create_code.data.p.n;//我是一条很长很长的用户昵称create_code.data.u.n
      this.item.views[2].text = create_code.data.p.cu;
      this.item.views[3].text = '《'+create_code.data.p.t+'》';//我是一条很长很长的作品标题create_code.data.p.t
      this.userInfo = create_code.data.u;
      this.postInfo = create_code.data.p;
      if(this.groupId==undefined || this.groupId==""){
        if(this.userInfo==undefined){
          this.returnText="回到首页";
        }else{
          this.returnText="回到个人主页";
        }
      }else{
        this.returnText="回到群页面";
      }
      this.drawImage();
      this.$apply();
    } else{
      wepy.showToast({
        title: create_code.msg
      });
    }
  }
  drawImage() {
    wepy.showLoading({
      title: '海报生成中',
      mask: true
    });
    this.palette = this.item;
    this.$apply();
  }

**Comment by CPPAlien** [comment]
可以看下卡在哪里了，理论上会有超时错误

**Comment by DengRiGuang** [comment]
图片数据和文字数据是拿到，一直绘制不出来，海报绘制中是在绘制完成才隐藏的。有什么方式可以抓取这个呢？

**Comment by CPPAlien** [comment]
有报什么错吗？

**Comment by DengRiGuang** [comment]
没什么报错
