### ISSUE TITLE
图片生成的文件是blob格式的

### ISSUE THREAD

**Issue by niuxiaowei** [Kujiale-Mobile/Painter#85]
在以下环境
SDKVersion":"2.5.0","brand":"iPhone","fontSizeSetting":16,"language":"zh-CN","model":"iPhone6","pixelRatio":2,"platform":"ios","screenHeight":700,"screenWidth":420,"statusBarHeight":20,"system":"iOS 10.0.1","version":"6.6.0","windowHeight":700,"windowWidth":420

生成的图片路径是blob:http://mmbiz.oa.com/670add7d-7b10-4ce6-a61b-921549252648这样的
请问下 什么情况下会出现这种情况，这域名又是从拿来的，多谢

**Comment by CPPAlien** [comment]
这域名我也没见过
