### ISSUE TITLE
请问生成名片，base64真机上无法显示

### ISSUE THREAD

**Issue by zhangkaicheng521** [Kujiale-Mobile/Painter#87]
二维码部分，展示的是 base64 后台返回的，小程序二维码，现在base64图片，无法合成到名片上。求解决。开发者工具可以正常显示，真机测试不可以

**Comment by CPPAlien** [comment]
一般让后台直接处理成图片返回链接比较好

**Comment by zhangkaicheng521** [comment]
我可以在谢谢小程序，生成本地路径，可以访问到吗？通过getFileSystemManager的方法，

**Comment by CPPAlien** [comment]
提前生成一张图片保存在本地也是可以的，直接是 base64，在小程序端，即使不用 canvas 绘图，也不好处理。

**Comment by zhangkaicheng521** [comment]
我直接图片，放在本地，然后我再传到cos上，生成名片的时候，直接去cos上获取，在真机测试的时候，打开手机调试可以生成二维码，关闭则不可以，大佬这是什么原因导致的？

**Comment by CPPAlien** [comment]
要在后台 download 域名那边添加白名单

**Comment by Wing-Li** [comment]
@zhangkaicheng521 
我来回答你。
请求二维码接口返回的是二进制流， 调用 wx.arrayBufferToBase64(res.data) 将其转为了base64。
然后，在调用如下接口，可以将流存到本地，它就成为了一张真正的图片，你可以做各种操作。
（将微信这二进制流在本地转成图片，真是不容易，微信真是够了。）

```
    var imgFileName = wx.env.USER_DATA_PATH + '/gameImage/xxx.png'
    var imageData = wx.arrayBufferToBase64(res.data) 

    const fileManager = wx.getFileSystemManager()
    fileManager.writeFile({
                filePath: imgFileName, // 本地文件目录
                data: imageData, // base64 数据
                encoding: 'base64',
                success(res) {
                  console.log(res)

                  // 开始生成 分享图
                  that.setData({
                    contentConfig: new GameShare().palette(user_icon, user_name, content, imgFileName),
                  })

                },
                fail(error) {
                  console.log(error)
                  wx.hideLoading()
                }
              })
```
***

### 重点来了，然后我想说的是
@CPPAlien 我们这个 image 的 url ，是不是不能显示 我存到微信本地的图片？

**Comment by Wing-Li** [comment]
对了，我在电脑上可以显示。
但是到了手机上就显示不出来了。

**Comment by CPPAlien** [comment]
@Wing-Li 有可能，你可以直接调用 canvas 的 drawImage 试试

**Comment by Wing-Li** [comment]
@CPPAlien 
canvas 的 drawImage 应该是可以绘制本地图片的。

“draw 方法是异步的，如果图片还没加载成功，有可能画出来的是空的。”
这一点，不知道我们程序有没有考虑到？我的手机很慢。
电脑 和 iphone 都可以，就我的 Android 不行。
