### ISSUE TITLE
能不能调用 js 来生成图片？只想获取图片的地址，自己来显示

### ISSUE THREAD

**Issue by Wing-Li** [Kujiale-Mobile/Painter#90]
#### 需求是：
想要生成一张尺寸比较大的图片，成功之后，再获取地址，显示到我指定的 Image 上。

#### 目前现状是：
必须要将 <painter /> 标签放在 .wxml 中，如果我用 style='display:none' 将它隐藏，图片就无法生成了。
现在每次图片生成后就会显示一张特别大的图。

有没有什么好的解决办法？
难道只能生成小尺寸的图片吗？

**Comment by Wing-Li** [comment]
给后来人一个可以达到效果的办法吧。
在 painter 标签上加上如下代码：
`style="position: absolute;left: -1000px;"`
如代码所示，是把它放到屏幕外面去了，这样用户就看不到了。

**Comment by CPPAlien** [comment]
是啊，一般都是这样做的，移动到屏幕外，canvas 绘图成功是有条件的，包括当前页面需要是 ready状态，并且不能被隐藏

**Comment by Wing-Li** [comment]
@CPPAlien 
好吧，那这个问题可以关了。
