### ISSUE TITLE
onImgOK事件相同的模板第二次就不执行了呢

### ISSUE THREAD

**Issue by rose-daniel** [Kujiale-Mobile/Painter#93]

**Comment by CPPAlien** [comment]
你看下你是不是用了 dirty

**Comment by tibic** [comment]
VM286484:1 getImageInfo failed, {"errMsg":"getImageInfo:fail invalid"}

同样的问题。第二次就获取失败了，临时图片是黑色的没有东西

**Comment by CPPAlien** [comment]
你是不是在页面还未加载完全的时候就进行了绘图
