### ISSUE TITLE
请问下，目前是否支持Taro框架

### ISSUE THREAD

**Issue by huangjianke** [Kujiale-Mobile/Painter#95]
如题，谢谢

**Comment by CPPAlien** [comment]
支持的，taro 框架天生支持原生内容

**Comment by huangjianke** [comment]
@CPPAlien 方便的话看是否能出个Taro集成的demo，目前Taro使用也很广了

**Comment by CPPAlien** [comment]
https://github.com/Kujiale-Mobile/Taro-Painter-Demo

**Comment by huangjianke** [comment]
@CPPAlien 感谢，之前已经在Taro框架集成了，方便的话看是否能添加到README.md案例展示里面

https://github.com/huangjianke/Gitter

**Comment by CPPAlien** [comment]
可以的，你可以提个 pr

**Comment by huangjianke** [comment]
@CPPAlien 
已提 
https://github.com/Kujiale-Mobile/Painter/pull/98
