### ISSUE TITLE
集成到自己工程后报Cannot read property 'toPx' of undefined错误

### ISSUE THREAD

**Issue by laoer** [Kujiale-Mobile/Painter#97]
painter.js? [sm]:86 Uncaught (in promise) TypeError: Cannot read property 'toPx' of undefined
    at painter.js? [sm]:86
    at <anonymous>

单独运行example时正常。

**Comment by lukaijin** [comment]
解决了吗

**Comment by aetherwu** [comment]
遇到相同问题。

**Comment by aetherwu** [comment]
https://github.com/Kujiale-Mobile/Painter/issues/124
