### ISSUE TITLE
三个问题：

### ISSUE THREAD

**Issue by xiaoshuoyiyi** [Kujiale-Mobile/Painter#99]
三个问题：
1、支持绘制小程序码吗？支持的话，应该选择哪种模式？
2、文字信息数据更新了，所绘制的内容并没有更新！（实例的数据也改变了，但显示的数据就是没有改变）
3、所绘制的图片URL改变了，但是所绘制的内容没有更新！

_Originally posted by @xiaoshuoyiyi in https://github.com/Kujiale-Mobile/Painter/issues/23#issuecomment-470812136_

**Comment by CPPAlien** [comment]
你只要把小程序码当作一张网络图片处理就行。另外两个应该是你代码的问题，请用例子试下
